name: ini_berapa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # VERSI SDK DIPERBAIKI: Menggunakan rentang versi yang valid
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.10.6 # Menggunakan versi stabil yang teruji
  flutter_tts: ^3.8.5 # Menggunakan versi stabil yang teruji
  
  # WAJIB DITAMBAHKAN: Untuk meminta izin akses kamera/mikrofon
  permission_handler: ^11.3.1

  # Dependensi Anda yang sudah ada (tidak diubah)
  # tflite_flutter: ^0.10.4 # Temporarily disabled for web testing
  image: ^4.1.7
  image_picker: ^1.1.2

  # TAMBAHKAN 3 PACKAGE DI BAWAH INI
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  intl: ^0.19.0

  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Versi lints disesuaikan

flutter:
  uses-material-design: true
  assets:
    - assets/models/yolov8n.tflite
    - assets/images/